export const jobs = [
  {
    id: 'frontend-engineer',
    title: 'Frontend Engineer',
    company: 'BrightLayer Labs',
    location: 'Bengaluru, India',
    type: 'Full time',
    workMode: 'Hybrid',
    salary: '₹18L - ₹28L',
    experience: '3-5 years',
    posted: '2 days ago',
    category: 'Engineering',
    applicants: 42,
    status: 'Approved',
    description:
      'Build polished hiring workflows for enterprise talent teams using React, design systems, and reusable frontend architecture.',
    requirements: [
      'Strong React, JavaScript, and CSS fundamentals',
      'Experience building dashboards or SaaS tools',
      'Comfortable working with APIs and product designers',
    ],
  },
  {
    id: 'product-designer',
    title: 'Product Designer',
    company: 'Northstar Careers',
    location: 'Remote',
    type: 'Contract',
    workMode: 'Remote',
    salary: '₹90K - ₹1.4L / mo',
    experience: '4+ years',
    posted: '1 week ago',
    category: 'Design',
    applicants: 19,
    status: 'Pending',
    description:
      'Shape intuitive candidate and recruiter experiences across search, applications, and analytics.',
    requirements: [
      'Portfolio showing complex product flows',
      'Strong UX writing and prototyping skills',
      'Experience with hiring or marketplace products is a plus',
    ],
  },
  {
    id: 'talent-acquisition-specialist',
    title: 'Talent Acquisition Specialist',
    company: 'PeopleGrid',
    location: 'Chennai, India',
    type: 'Full time',
    workMode: 'On site',
    salary: '₹7L - ₹11L',
    experience: '2-4 years',
    posted: '3 days ago',
    category: 'Recruiting',
    applicants: 63,
    status: 'Approved',
    description:
      'Own sourcing, screening, and interview coordination for fast-growing technology teams.',
    requirements: [
      'Hands-on sourcing experience',
      'Excellent stakeholder communication',
      'Able to manage applicant pipelines with clear follow-up',
    ],
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    company: 'MetricWorks',
    location: 'Hyderabad, India',
    type: 'Full time',
    workMode: 'Hybrid',
    salary: '₹10L - ₹16L',
    experience: '2+ years',
    posted: 'Today',
    category: 'Analytics',
    applicants: 27,
    status: 'Approved',
    description:
      'Turn hiring and workforce data into clear insights for leadership dashboards and recruiter performance reports.',
    requirements: [
      'Advanced SQL and spreadsheet skills',
      'Experience with BI dashboards',
      'Ability to explain patterns in plain business language',
    ],
  },
  {
    id: 'backend-engineer',
    title: 'Backend Engineer',
    company: 'CloudNest Systems',
    location: 'Pune, India',
    type: 'Full time',
    workMode: 'Hybrid',
    salary: 'INR 16L - INR 26L',
    experience: '3-6 years',
    posted: '1 day ago',
    category: 'Engineering',
    applicants: 35,
    status: 'Approved',
    description:
      'Design reliable APIs, data models, and backend services that power hiring workflows at scale.',
    requirements: [
      'Strong Node.js or Java backend experience',
      'Comfortable with databases, queues, and REST APIs',
      'Experience improving performance and reliability',
    ],
  },
  {
    id: 'hr-operations-manager',
    title: 'HR Operations Manager',
    company: 'HireBridge',
    location: 'Mumbai, India',
    type: 'Full time',
    workMode: 'On site',
    salary: 'INR 12L - INR 18L',
    experience: '5+ years',
    posted: '4 days ago',
    category: 'Human Resources',
    applicants: 51,
    status: 'Approved',
    description:
      'Lead HR operations, onboarding, documentation, and employee support for a growing services team.',
    requirements: [
      'Experience managing HR policies and employee lifecycle processes',
      'Strong documentation and compliance skills',
      'Able to coordinate with finance, recruitment, and leadership teams',
    ],
  },
  {
    id: 'digital-marketing-executive',
    title: 'Digital Marketing Executive',
    company: 'LaunchLoop Media',
    location: 'Remote',
    type: 'Full time',
    workMode: 'Remote',
    salary: 'INR 6L - INR 9L',
    experience: '1-3 years',
    posted: 'Today',
    category: 'Marketing',
    applicants: 44,
    status: 'Approved',
    description:
      'Run digital campaigns, optimize job promotion funnels, and report on channel performance.',
    requirements: [
      'Hands-on experience with paid search and social campaigns',
      'Good understanding of analytics and conversion tracking',
      'Clear writing skills for ads, emails, and landing pages',
    ],
  },
  {
    id: 'customer-success-manager',
    title: 'Customer Success Manager',
    company: 'TalentPulse',
    location: 'Gurugram, India',
    type: 'Full time',
    workMode: 'Hybrid',
    salary: 'INR 11L - INR 17L',
    experience: '3+ years',
    posted: '5 days ago',
    category: 'Customer Success',
    applicants: 28,
    status: 'Pending',
    description:
      'Partner with recruiter clients to improve adoption, reduce churn, and turn feedback into product insight.',
    requirements: [
      'Experience managing B2B SaaS customer accounts',
      'Strong presentation and relationship-building skills',
      'Ability to translate customer needs into practical action plans',
    ],
  },
  {
    id: 'qa-automation-engineer',
    title: 'QA Automation Engineer',
    company: 'VeritySoft',
    location: 'Kochi, India',
    type: 'Full time',
    workMode: 'Remote',
    salary: 'INR 9L - INR 14L',
    experience: '2-5 years',
    posted: '6 days ago',
    category: 'Quality Assurance',
    applicants: 22,
    status: 'Approved',
    description:
      'Create automated test coverage for candidate journeys, recruiter tools, and application workflows.',
    requirements: [
      'Experience with Playwright, Cypress, or Selenium',
      'Strong test planning and bug reporting habits',
      'Comfortable testing APIs and frontend flows',
    ],
  },
  {
    id: 'business-development-associate',
    title: 'Business Development Associate',
    company: 'CareerWay Partners',
    location: 'Delhi, India',
    type: 'Full time',
    workMode: 'On site',
    salary: 'INR 5L - INR 8L',
    experience: '0-2 years',
    posted: '1 week ago',
    category: 'Sales',
    applicants: 67,
    status: 'Approved',
    description:
      'Find new employer partners, qualify leads, and support sales conversations for hiring solutions.',
    requirements: [
      'Strong communication and follow-up skills',
      'Comfortable with outbound calls and CRM updates',
      'Interest in recruitment technology and employer branding',
    ],
  },
  {
    id: 'devops-engineer',
    title: 'DevOps Engineer',
    company: 'StackHarbor',
    location: 'Bengaluru, India',
    type: 'Contract',
    workMode: 'Hybrid',
    salary: 'INR 1.2L - INR 1.8L / mo',
    experience: '4-7 years',
    posted: '2 days ago',
    category: 'Engineering',
    applicants: 17,
    status: 'Approved',
    description:
      'Improve cloud infrastructure, deployment pipelines, monitoring, and release reliability for product teams.',
    requirements: [
      'Experience with AWS, Docker, and CI/CD pipelines',
      'Strong scripting and troubleshooting skills',
      'Knowledge of monitoring, alerts, and incident response',
    ],
  },
  {
    id: 'content-writer',
    title: 'Content Writer',
    company: 'WorkStory Studio',
    location: 'Remote',
    type: 'Part time',
    workMode: 'Remote',
    salary: 'INR 35K - INR 55K / mo',
    experience: '1+ years',
    posted: '3 days ago',
    category: 'Content',
    applicants: 39,
    status: 'Pending',
    description:
      'Write employer profiles, career advice, email content, and job-market stories for candidates and recruiters.',
    requirements: [
      'Strong writing portfolio with clear, useful content',
      'Able to research roles, industries, and hiring trends',
      'Comfortable editing for tone, clarity, and search visibility',
    ],
  },
]
